
module.exports = {
    '1': 'Medico chirurgo',
    '2': 'Odontoiatra',
    '3': 'Farmacista',
    '4': 'Veterinario',
    '5': 'Psicologo',
    '6': 'Biologo',
    '7': 'Chimico',
    '8': 'Fisico',
    '9': 'Assistente sanitario',
    '10': 'Dietista',
    '11': 'Educatore professionale',
    '12': 'Fisioterapista',
    '13': 'Igienista dentale',
    '14': 'Infermiere',
    '15': 'Infermiere pediatrico',
    '16': 'Logopedista',
    '17': 'Ortottista/assistente di oftalmologia',
    '18': 'Ostetrica/o',
    '19': 'Podologo',
    '20': 'Tecnico audiometrista',
    '21': 'Tecnico audioprotesista',
    '22': 'Tecnico della fisiopatologia cardiocircolatoria e perfusione cardiovascolare',
    '23': 'Tecnico della prevenzione nell\'ambiente e nei luoghi di lavoro',
    '24': 'Tecnico della riabilitazione psichiatrica',
    '25': 'Tecnico di neurofisiopatologia',
    '26': 'Tecnico ortopedico',
    '27': 'Tecnico sanitario di radiologia medica',
    '28': 'Tecnico sanitario laboratorio biomedico',
    '29': 'Terapista della neuro e psicomotricità dell\'età evolutiva',
    '30': 'Terapista occupazionale',
    '99': 'Tutte le professioni'
};
